CREATE TABLE Menu
(
	MenuID int Primary key Identity(1,1),
	TENMON Nvarchar(200) NOT NULL,
	GIA DECIMAL(18,2) NOT NULL,
	LOAIMON NVARCHAR(50),
	HINHANH NVARCHAR(MAX),
	HIENTHI BIT,
)

CREATE TABLE Ban
(
	BanID int Primary key Identity(1,1),
	SOBAN INT NOT NULL,
	TINHTRANG NVARCHAR(50) NOT NULL,
)

CREATE TABLE NhanVien (
    MaNV CHAR(10) PRIMARY KEY NOT NULL, 
    TENNV NVARCHAR(100) NOT NULL,       
    GIOITINH BIT NOT NULL,   
    SDT VARCHAR(15)            
);
ALTER TABLE NhanVien
ADD HIENTHI BIT

CREATE TABLE HoaDon (
    SOHOADON INT PRIMARY KEY,
    NGAYDAT DATETIME DEFAULT GETDATE(),
	MaNV CHAR(10) NOT NULL, 
	CONSTRAINT FK_HoaDon_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) 
);
ALTER TABLE HoaDon -- chua load
ADD TONGTIEN DECIMAL(18,2) 

CREATE TABLE ChiTietHoaDon
(  
    SOHOADON INT NOT NULL,  
    MenuID INT,  
    SOLUONG INT NOT NULL, 
	CONSTRAINT PK_ChiTietHoaDon PRIMARY KEY (SOHOADON, MenuID),
    CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (SOHOADON) REFERENCES HoaDon(SOHOADON), 
    CONSTRAINT FK_ChiTietHoaDon_Menu FOREIGN KEY (MenuID) REFERENCES Menu(MenuID)
);

CREATE TABLE DangKy (
    MaDK INT PRIMARY KEY IDENTITY(1,1),
    TenDK NVARCHAR(50) NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    ChucVu BIT NOT NULL,
    MaNV CHAR(10) NOT NULL,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
);

/*CREATE TABLE ThongKe (
    ThongKeID INT PRIMARY KEY IDENTITY(1,1), 
    NGAY DATETIME DEFAULT GETDATE() NOT NULL,                      
    DOANHTHU DECIMAL(18,2) NOT NULL,         
    SOHOADON INT NOT NULL,                   
    FOREIGN KEY (SOHOADON) REFERENCES HoaDon(SOHOADON)
);*/